/**
 * iroh-http-node — Node.js entry point.
 *
 * Wires the napi-rs native addon to iroh-http-shared and exports `createNode`.
 *
 * ```ts
 * import { createNode } from 'iroh-http-node';
 *
 * const node = await createNode({ key: savedKey });
 * node.serve({}, req => new Response('hello'));
 * const res = await node.fetch(peerId, '/api');
 * ```
 */

// The napi-rs build tool generates this file at build time.
// It loads the correct platform-specific .node binary.
import {
  createEndpoint,
  closeEndpoint,
  jsNextChunk,
  jsSendChunk,
  jsFinishBody,
  jsAllocBodyWriter,
  jsCancelRequest,
  jsNextTrailer,
  jsSendTrailers,
  rawFetch as napiRawFetch,
  rawServe as napiRawServe,
  rawConnect as napiRawConnect,
} from "./iroh-http-node.node";  // generated by napi build

import {
  buildNode,
  type Bridge,
  type RawFetchFn,
  type RawServeFn,
  type RawConnectFn,
  type AllocBodyWriterFn,
  type NodeOptions,
  type IrohNode,
  type FfiResponse,
  type FfiDuplexStream,
  type RequestPayload,
  type FfiResponseHead,
  classifyBindError,
  type SecretKey,
} from "iroh-http-shared";

// ── Bridge implementation ─────────────────────────────────────────────────────

const bridge: Bridge = {
  nextChunk: (handle: number) => jsNextChunk(handle),
  sendChunk: (handle: number, chunk: Uint8Array) => jsSendChunk(handle, chunk),
  finishBody: (handle: number) => {
    jsFinishBody(handle);
    return Promise.resolve();
  },
  cancelRequest: (handle: number) => {
    jsCancelRequest(handle);
    return Promise.resolve();
  },
  nextTrailer: async (handle: number) => {
    const rows = await jsNextTrailer(handle);
    return rows ? (rows as string[][]).map((p) => [p[0], p[1]] as [string, string]) : null;
  },
  sendTrailers: (handle: number, trailers: [string, string][]) => {
    jsSendTrailers(handle, trailers as string[][]);
    return Promise.resolve();
  },
};

// ── Platform function adapters ────────────────────────────────────────────────

const rawFetch: RawFetchFn = async (
  endpointHandle,
  nodeId,
  url,
  method,
  headers,
  reqBodyHandle
) => {
  const res = await napiRawFetch(
    endpointHandle,
    nodeId,
    url,
    method,
    headers as string[][],
    reqBodyHandle ?? null
  );
  return {
    status: res.status,
    headers: res.headers as [string, string][],
    bodyHandle: res.bodyHandle,
    url: res.url,
    trailersHandle: res.trailersHandle,
  } satisfies FfiResponse;
};

const rawServe: RawServeFn = (
  endpointHandle,
  _options,
  callback: (payload: RequestPayload) => Promise<FfiResponseHead>
) => {
  napiRawServe(
    endpointHandle,
    async (payload: Record<string, unknown>) => {
      const typed = payload as unknown as RequestPayload;
      const head = await callback(typed);
      return {
        status: head.status,
        headers: head.headers as string[][],
      };
    }
  );
};

const allocBodyWriter: AllocBodyWriterFn = () => jsAllocBodyWriter();

const rawConnect: RawConnectFn = async (
  endpointHandle,
  nodeId,
  path,
  headers
) => {
  const ffi = await napiRawConnect(
    endpointHandle,
    nodeId,
    path,
    headers as string[][]
  );
  return {
    readHandle: ffi.readHandle,
    writeHandle: ffi.writeHandle,
  } satisfies FfiDuplexStream;
};

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Create an Iroh node for peer-to-peer HTTP.
 *
 * @param options Optional configuration.  Omit `key` to generate a fresh identity.
 */
export async function createNode(options?: NodeOptions): Promise<IrohNode> {
  const keyBytes: Uint8Array | null = options?.key
    ? (options.key instanceof Uint8Array ? options.key : (options.key as SecretKey).toBytes())
    : null;

  const info = await createEndpoint(
    options
      ? {
          key: keyBytes,
          idleTimeout: options.idleTimeout ?? null,
          relays: options.relays ?? null,
          dnsDiscovery: options.dnsDiscovery ?? null,
        }
      : null
  ).catch((e: unknown) => { throw classifyBindError(e); });

  return buildNode(
    bridge,
    {
      endpointHandle: info.endpointHandle,
      nodeId: info.nodeId,
      keypair: info.keypair as Uint8Array,
    },
    rawFetch,
    rawServe,
    rawConnect,
    allocBodyWriter,
    (handle) => closeEndpoint(handle)
  );
}
