/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsNodeOptions {
  key?: Uint8Array
  idleTimeout?: number
  relayMode?: string
  relays?: Array<string>
  bindAddrs?: Array<string>
  dnsDiscovery?: string
  dnsDiscoveryEnabled?: boolean
  channelCapacity?: number
  maxChunkSizeBytes?: number
  handleTtl?: number
  sweepInterval?: number
  maxPooledConnections?: number
  poolIdleTimeoutMs?: number
  disableNetworking?: boolean
  proxyUrl?: string
  proxyFromEnv?: boolean
  keylog?: boolean
  compressionLevel?: number
  compressionMinBodyBytes?: number
  /** Maximum header block size in bytes.  Default: 65536. */
  maxHeaderBytes?: number
}
/** Info returned after a successful `createEndpoint` call. */
export interface JsEndpointInfo {
  /** Opaque handle for the endpoint — pass to all bridge functions. */
  endpointHandle: number
  /** Base32-encoded public key (stable node identity). */
  nodeId: string
  /** 32-byte Ed25519 secret key — store to restore the same identity. */
  keypair: Uint8Array
}
/**
 * Bind an Iroh QUIC endpoint and return a handle for subsequent operations.
 *
 * This is the entry point for creating an iroh-http node. Pass `None` for
 * all-default configuration or supply a `JsNodeOptions` to customise.
 */
export declare function createEndpoint(options?: JsNodeOptions | undefined | null): Promise<JsEndpointInfo>
/**
 * Close an Iroh endpoint.
 *
 * If `force` is `true`, aborts immediately without draining in-flight
 * requests.  Otherwise performs a graceful shutdown.
 */
export declare function closeEndpoint(endpointHandle: number, force?: boolean | undefined | null): Promise<void>
/** Discovery event returned by `mdnsNextEvent`. */
export interface JsPeerDiscoveryEvent {
  /** `true` = peer appeared; `false` = peer expired. */
  isActive: boolean
  /** Base32 public key of the discovered peer. */
  nodeId: string
  /** Known addresses: relay URLs and/or `ip:port` strings. */
  addrs: Array<string>
}
/**
 * Start a browse session: discover peers on the local network via mDNS.
 * Returns a browse handle for polling events.
 */
export declare function mdnsBrowse(endpointHandle: number, serviceName: string): Promise<number>
/**
 * Poll the next discovery event from a browse session.
 * Returns `null` when the session is closed.
 */
export declare function mdnsNextEvent(browseHandle: number): Promise<JsPeerDiscoveryEvent | null>
/** Close a browse session, stopping mDNS discovery. */
export declare function mdnsBrowseClose(browseHandle: number): void
/**
 * Start advertising this node on the local network via mDNS.
 * Returns an advertise handle.
 */
export declare function mdnsAdvertise(endpointHandle: number, serviceName: string): number
/** Stop advertising this node on the local network. */
export declare function mdnsAdvertiseClose(advertiseHandle: number): void
export interface JsNodeAddrInfo {
  id: string
  addrs: Array<string>
}
export interface JsPathInfo {
  relay: boolean
  addr: string
  active: boolean
}
export interface JsPeerStats {
  relay: boolean
  relayUrl?: string
  paths: Array<JsPathInfo>
  rttMs?: number
  /**
   * Network byte/packet counters are exposed as `f64` (not `i64`) so that
   * values exceeding i64::MAX remain positive in JavaScript rather than
   * wrapping to negative.  Values above 2^53 lose integer precision, but
   * that represents >9 petabytes and is acceptable for telemetry purposes.
   */
  bytesSent?: number
  bytesReceived?: number
  lostPackets?: number
  sentPackets?: number
  congestionWindow?: number
}
/** Full node address: node ID + relay URL(s) + direct socket addresses. */
export declare function nodeAddr(endpointHandle: number): JsNodeAddrInfo
/**
 * Generate a ticket string for the given endpoint.
 *
 * The ticket encodes the node ID and all known addresses (relay URLs + direct IPs).
 * Share with peers so they can connect directly.
 */
export declare function nodeTicket(endpointHandle: number): string
/** Home relay URL, or null if not connected to a relay. */
export declare function homeRelay(endpointHandle: number): string | null
/** Known addresses for a remote peer, or null if unknown. */
export declare function peerInfo(endpointHandle: number, nodeId: string): Promise<JsNodeAddrInfo | null>
/** Per-peer connection statistics with path information. */
export declare function peerStats(endpointHandle: number, nodeId: string): Promise<JsPeerStats | null>
/** Endpoint-level observability snapshot. */
export interface JsEndpointStats {
  activeReaders: number
  activeWriters: number
  activeSessions: number
  totalHandles: number
  poolSize: number
  activeConnections: number
  activeRequests: number
}
/** Snapshot of current endpoint statistics (point-in-time). */
export declare function endpointStats(endpointHandle: number): JsEndpointStats
/**
 * Register a push callback for transport-level events.
 *
 * Spawns a Tokio task that drains the endpoint's event channel and calls
 * `handler` on the Node.js thread for each event (JSON-serialised string).
 * The task exits automatically when the endpoint closes (all senders drop).
 * Call at most once per endpoint; subsequent calls return an error.
 */
export declare function startTransportEvents(endpointHandle: number, handler: (...args: any[]) => any): void
/**
 * Subscribe to path changes for a specific peer.
 * Returns the next path change as a JSON string, or null when done.
 * Call repeatedly to receive successive changes; the endpoint de-duplicates
 * watcher tasks so concurrent calls for the same peer share one Rust task.
 */
export declare function nextPathChange(endpointHandle: number, nodeId: string): Promise<string | null>
/**
 * Read the next chunk from a body reader handle.
 *
 * Returns `null` at EOF. The handle is automatically cleaned up after EOF.
 */
export declare function jsNextChunk(endpointHandle: number, handle: bigint): Promise<Buffer | null>
/**
 * Non-blocking body read fast path.
 *
 * Returns:
 * - `Ok(Some(chunk))` — data was available synchronously.
 * - `Ok(None)` — EOF, handle cleaned up.
 * - `Err(_)` — channel empty or lock contended, caller should fall back to async `nextChunk`.
 */
export declare function jsTryNextChunk(endpointHandle: number, handle: bigint): Buffer | null
/**
 * Push a chunk into a body writer handle.
 *
 * Large chunks are automatically split to stay within backpressure limits.
 */
export declare function jsSendChunk(endpointHandle: number, handle: bigint, chunk: Uint8Array): Promise<void>
/**
 * Signal end-of-body by dropping the writer.
 *
 * The paired `BodyReader` will return `null` on its next `nextChunk` call.
 */
export declare function jsFinishBody(endpointHandle: number, handle: bigint): void
/** Cancel a body reader, causing any pending `nextChunk` to return null. */
export declare function jsCancelRequest(endpointHandle: number, handle: bigint): void
/**
 * Allocate a body writer handle for streaming request bodies.
 *
 * Call this before `rawFetch` to get a handle that can be written to
 * with `sendChunk` / `finishBody`.
 */
export declare function jsAllocBodyWriter(endpointHandle: number): bigint
/**
 * Allocate a cancellation token for an upcoming `rawFetch` call.
 *
 * Wire `AbortSignal → cancelInFlight(token)` for request cancellation.
 */
export declare function jsAllocFetchToken(endpointHandle: number): bigint
/**
 * Cancel an in-flight fetch by its cancellation token.
 *
 * Safe to call after the fetch has already completed (no-op).
 */
export declare function jsCancelInFlight(endpointHandle: number, token: bigint): void
/**
 * Raw response returned by `rawFetch`.
 *
 * The shared TS layer wraps this into a web-standard `Response`.
 */
export interface JsFfiResponse {
  /** HTTP status code. */
  status: number
  /** Response headers as `[[key, value], ...]`. */
  headers: Array<Array<string>>
  /** Handle to the response body reader (`nextChunk`). */
  bodyHandle: bigint
  /** Full `httpi://` URL of the responding peer. */
  url: string
}
/**
 * Send an HTTP request to a remote Iroh peer.
 *
 * Low-level function — the shared TS layer wraps this in `makeFetch`.
 */
export declare function rawFetch(endpointHandle: number, nodeId: string, url: string, method: string, headers: Array<Array<string>>, reqBodyHandle: bigint | undefined | null, fetchToken: bigint, directAddrs?: Array<string> | undefined | null): Promise<JsFfiResponse>
/**
 * Call once per request from the JS handler to send the response head.
 *
 * This is the Node.js equivalent of Tauri's `respond_to_request` command.
 * The handler callback in `rawServe` is fire-and-forget (napi-rs does not
 * support awaiting Promise return values from ThreadsafeFunction callbacks),
 * so JS must call `rawRespond` explicitly after computing the response head.
 */
export declare function rawRespond(endpointHandle: number, reqHandle: bigint, status: number, headers: Array<Array<string>>): void
/** Server-side configuration passed at `serve()` time. */
export interface JsServeOptions {
  /** Maximum simultaneous in-flight requests.  Default: 1024. */
  maxConcurrency?: number
  /** Maximum connections from a single peer.  Default: 8. */
  maxConnectionsPerPeer?: number
  /** Per-request timeout in milliseconds.  Default: 60 000.  0 = disabled. */
  requestTimeout?: number
  /** Reject request bodies larger than this many bytes.  Default: unlimited. */
  maxRequestBodyBytes?: number
  /** Maximum total QUIC connections the server will accept.  Default: unlimited. */
  maxTotalConnections?: number
  /** Maximum serve errors before shutdown.  Default: 5. */
  maxServeErrors?: number
  /** Drain timeout in milliseconds after shutdown signal.  Default: 5000. */
  drainTimeout?: number
  /** Enable load-shedding (reject with 503 when at capacity). */
  loadShed?: boolean
}
export declare function rawServe(endpointHandle: number, serveOptions: JsServeOptions | undefined | null, handler: (...args: any[]) => any, onConnectionEvent?: (...args: any[]) => any | undefined | null): void
/**
 * Stop the serve loop for the given endpoint (graceful shutdown).
 *
 * This signals the accept loop to stop but does NOT close the endpoint or
 * drain in-flight requests.  Call `closeEndpoint` afterwards if you want
 * a full teardown.
 */
export declare function stopServe(endpointHandle: number): void
/**
 * Wait until the serve loop has fully exited (all in-flight requests drained).
 *
 * Resolves immediately if `rawServe` was never called on this endpoint.
 * Call this after `stopServe` to confirm the loop has actually terminated.
 */
export declare function waitServeStop(endpointHandle: number): Promise<void>
/**
 * Wait until this endpoint has been fully closed — either because `closeEndpoint()`
 * was called or because the QUIC stack shut down natively.
 *
 * This is used to surface `node.closed` reliably even without an explicit `close()`.
 */
export declare function waitEndpointClosed(endpointHandle: number): Promise<void>
/**
 * Establish a session (QUIC connection) to a remote peer.
 * Returns an opaque session handle.
 */
export declare function sessionConnect(endpointHandle: number, nodeId: string, directAddrs?: Array<string> | undefined | null): Promise<bigint>
/**
 * Accept an incoming session (QUIC connection) from a remote peer.
 *
 * Blocks until a peer connects or the endpoint shuts down.  Returns
 * `{ sessionHandle, nodeId }` on success, or `null` when the endpoint is closed.
 */
export interface JsSessionAccepted {
  sessionHandle: bigint
  nodeId: string
}
export declare function sessionAccept(endpointHandle: number): Promise<JsSessionAccepted | null>
/** Open a new bidirectional stream on an existing session. */
export interface JsSessionBidiStream {
  readHandle: bigint
  writeHandle: bigint
}
export declare function sessionCreateBidiStream(endpointHandle: number, sessionHandle: bigint): Promise<JsSessionBidiStream>
/**
 * Accept the next incoming bidirectional stream on a session.
 * Returns null when the session is closed.
 */
export declare function sessionNextBidiStream(endpointHandle: number, sessionHandle: bigint): Promise<JsSessionBidiStream | null>
/** Close a session. */
export declare function sessionCloseHandle(endpointHandle: number, sessionHandle: bigint, closeCode?: bigint | undefined | null, reason?: string | undefined | null): Promise<void>
/** Wait for a session to close. Returns close info { closeCode, reason }. */
export interface JsCloseInfo {
  closeCode: bigint
  reason: string
}
export declare function sessionClosed(endpointHandle: number, sessionHandle: bigint): Promise<JsCloseInfo>
/**
 * Open a new unidirectional (send-only) stream on a session.
 * Returns a write handle.
 */
export declare function sessionCreateUniStream(endpointHandle: number, sessionHandle: bigint): Promise<bigint>
/**
 * Accept the next incoming unidirectional stream on a session.
 * Returns a read handle, or null when the session is closed.
 */
export declare function sessionNextUniStream(endpointHandle: number, sessionHandle: bigint): Promise<bigint | null>
/** Send a datagram on a session. */
export declare function sessionSendDatagram(endpointHandle: number, sessionHandle: bigint, data: Uint8Array): Promise<void>
/** Receive the next datagram on a session. Returns null when the session closes. */
export declare function sessionRecvDatagram(endpointHandle: number, sessionHandle: bigint): Promise<Buffer | null>
/**
 * Get the maximum datagram payload size for a session.
 * Returns null if datagrams are not supported.
 */
export declare function sessionMaxDatagramSize(endpointHandle: number, sessionHandle: bigint): number | null
/**
 * Sign arbitrary bytes with a 32-byte Ed25519 secret key.
 * Returns a 64-byte signature as a `Buffer`.
 */
export declare function secretKeySign(secretKey: Uint8Array, data: Uint8Array): Buffer
/**
 * Verify a 64-byte Ed25519 signature against a 32-byte public key.
 * Returns `true` on success, `false` on failure — does not throw.
 */
export declare function publicKeyVerify(publicKey: Uint8Array, data: Uint8Array, signature: Uint8Array): boolean
/** Generate a fresh Ed25519 secret key. Returns 32 raw bytes. */
export declare function generateSecretKey(): Buffer
