/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Advertise a generic DNS-SD service. Returns an advertise handle. */
export declare function advertise(config: JsServiceConfig): Promise<number>

/** Stop a generic DNS-SD advertisement. */
export declare function advertiseClose(advertiseHandle: number): void

/**
 * Start advertising this node on the local network via mDNS.
 * Returns an advertise handle.
 *
 * Declared `async` so napi runs it inside the global Tokio runtime. The mDNS
 * address-lookup constructor calls `tokio::runtime::Handle::current()`, which
 * panics outside a runtime context. A synchronous binding ran on the bare JS
 * thread and could panic—aborting the process under `panic = "abort"`—when
 * invoked from a late promise continuation during `--test-force-exit` teardown
 * (issue #243). Running inside the runtime keeps the handle valid and lets
 * post-shutdown calls reject gracefully instead of aborting.
 */
export declare function advertisePeer(endpointHandle: number, serviceName: string): Promise<number>

/** Stop advertising this node on the local network. */
export declare function advertisePeerClose(advertiseHandle: number): void

/**
 * Browse for a generic DNS-SD service. Returns a browse handle for polling
 * records via `browseNext`.
 */
export declare function browse(serviceName: string, protocol?: string | undefined | null): Promise<number>

/** Close a generic DNS-SD browse session. */
export declare function browseClose(browseHandle: number): void

/**
 * Poll the next record from a generic DNS-SD browse session.
 * Returns `null` when the session is closed.
 */
export declare function browseNext(browseHandle: number): Promise<JsServiceRecord | null>

/**
 * Start a browse session: discover peers on the local network via mDNS.
 * Returns a browse handle for polling events.
 */
export declare function browsePeers(endpointHandle: number, serviceName: string): Promise<number>

/** Close a browse session, stopping mDNS discovery. */
export declare function browsePeersClose(browseHandle: number): void

/**
 * Poll the next discovery event from a browse session.
 * Returns `null` when the session is closed.
 */
export declare function browsePeersNext(browseHandle: number): Promise<JsPeerDiscoveryEvent | null>

/**
 * Close an Iroh endpoint.
 *
 * If `force` is `true`, aborts immediately without draining in-flight
 * requests.  Otherwise performs a graceful shutdown.
 *
 * The endpoint is removed from the registry **after** closing, not before.
 * This ensures that background tasks (transport events, serve callbacks)
 * that need the endpoint handle during the drain period can still look it up.
 */
export declare function closeEndpoint(endpointHandle: number, force?: boolean | undefined | null): Promise<void>

/**
 * Bind an Iroh QUIC endpoint and return a handle for subsequent operations.
 *
 * This is the entry point for creating an iroh-http node. Pass `None` for
 * all-default configuration or supply a `JsNodeOptions` to customise.
 */
export declare function createEndpoint(options?: JsNodeOptions | undefined | null): Promise<JsEndpointInfo>

/**
 * Discovery info: node id + dialable direct `ip:port` address + relay URL.
 *
 * `directAddress` carries the real bound QUIC port (or null when only
 * loopback/link-local addresses are available); safe to advertise for
 * LAN direct-dial. `directAddresses` carries *all* routable candidates so an
 * advertiser can publish them and let the dialer race the paths (#348).
 */
export declare function discoveryInfo(endpointHandle: number): JsDiscoveryInfo

/** Snapshot of current endpoint statistics (point-in-time). */
export declare function endpointStats(endpointHandle: number): JsEndpointStats

/** Generate a fresh Ed25519 secret key. Returns 32 raw bytes. */
export declare function generateSecretKey(): Buffer

/** Home relay URL, or null if not connected to a relay. */
export declare function homeRelay(endpointHandle: number): string | null

/**
 * Allocate a body writer handle for streaming request bodies.
 *
 * Call this before `rawFetch` to get a handle that can be written to
 * with `sendChunk` / `finishBody`.
 */
export declare function jsAllocBodyWriter(endpointHandle: number): bigint

/**
 * Allocate a cancellation token for an upcoming `rawFetch` call.
 *
 * Wire `AbortSignal → cancelInFlight(token)` for request cancellation.
 */
export declare function jsAllocFetchToken(endpointHandle: number): bigint

/**
 * napi v3 payload for `rawServe` handler callbacks.
 *
 * Replaces manual `env.create_*()` construction from napi v2.
 * Fields mirror `RequestPayload` but use napi-compatible types:
 * `BigInt` for opaque u64 handles, `Vec<Vec<String>>` for headers.
 */
export interface JsCallArgs {
  reqHandle: bigint
  reqBodyHandle: bigint
  resBodyHandle: bigint
  isBidi: boolean
  method: string
  url: string
  remoteNodeId: string
  /** `[[name, value], ...]` */
  headers: Array<Array<string>>
}

/**
 * Cancel an in-flight fetch by its cancellation token.
 *
 * Safe to call after the fetch has already completed (no-op).
 */
export declare function jsCancelInFlight(endpointHandle: number, token: bigint): void

/** Cancel a body reader, causing any pending `nextChunk` to return null. */
export declare function jsCancelRequest(endpointHandle: number, handle: bigint): void

/** Wait for a session to close. Returns close info { closeCode, reason }. */
export interface JsCloseInfo {
  closeCode: bigint
  reason: string
}

/** napi v3 payload for `rawServe` connection-event callbacks. */
export interface JsConnectionEvent {
  peerId: string
  connected: boolean
}

export interface JsDiscoveryInfo {
  nodeId: string
  directAddress?: string
  directAddresses: Array<string>
  relayUrl?: string
}

/** Info returned after a successful `createEndpoint` call. */
export interface JsEndpointInfo {
  /** Opaque handle for the endpoint — pass to all bridge functions. */
  endpointHandle: number
  /** Base32-encoded public key (stable node identity). */
  nodeId: string
}

/** Endpoint-level observability snapshot. */
export interface JsEndpointStats {
  activeReaders: number
  activeWriters: number
  activeSessions: number
  totalHandles: number
  poolSize: number
  activeConnections: number
  activeRequests: number
  activePathSubscriptions: number
  activePathWatchers: number
}

/**
 * Raw response returned by `rawFetch`.
 *
 * The shared TS layer wraps this into a web-standard `Response`.
 */
export interface JsFfiResponse {
  /** HTTP status code. */
  status: number
  /** Response headers as `[[key, value], ...]`. */
  headers: Array<Array<string>>
  /** Handle to the response body reader (`nextChunk`). */
  bodyHandle: bigint
  /** Full `httpi://` URL of the responding peer. */
  url: string
}

/**
 * Signal end-of-body by dropping the writer.
 *
 * The paired `BodyReader` will return `null` on its next `nextChunk` call.
 */
export declare function jsFinishBody(endpointHandle: number, handle: bigint): void

/**
 * Read the next chunk from a body reader handle.
 *
 * Returns `null` at EOF. The handle is automatically cleaned up after EOF.
 */
export declare function jsNextChunk(endpointHandle: number, handle: bigint): Promise<Buffer | null>

export interface JsNodeAddrInfo {
  id: string
  addrs: Array<string>
}

export interface JsNodeOptions {
  key?: Uint8Array
  idleTimeout?: number
  relayMode?: string
  relays?: Array<string>
  bindAddrs?: Array<string>
  dnsDiscovery?: string
  dnsDiscoveryEnabled?: boolean
  channelCapacity?: number
  maxChunkSizeBytes?: number
  handleTtl?: number
  sweepInterval?: number
  maxPooledConnections?: number
  poolIdleTimeoutMs?: number
  disableNetworking?: boolean
  proxyUrl?: string
  proxyFromEnv?: boolean
  keylog?: boolean
  compressionLevel?: number
  compressionMinBodyBytes?: number
  /** Maximum header block size in bytes.  Default: 65536. */
  maxHeaderBytes?: number
}

export interface JsPathInfo {
  relay: boolean
  addr: string
  active: boolean
}

/** Discovery event returned by `browsePeersNext`. */
export interface JsPeerDiscoveryEvent {
  /** `true` = peer appeared; `false` = peer expired. */
  isActive: boolean
  /** Base32 public key of the discovered peer. */
  nodeId: string
  /** Known addresses: relay URLs and/or `ip:port` strings. */
  addrs: Array<string>
}

export interface JsPeerStats {
  relay: boolean
  relayUrl?: string
  paths: Array<JsPathInfo>
  rttMs?: number
  /**
   * Network byte/packet counters are exposed as `f64` (not `i64`) so that
   * values exceeding i64::MAX remain positive in JavaScript rather than
   * wrapping to negative.  Values above 2^53 lose integer precision, but
   * that represents >9 petabytes and is acceptable for telemetry purposes.
   */
  bytesSent?: number
  bytesReceived?: number
  lostPackets?: number
  sentPackets?: number
  congestionWindow?: number
}

/**
 * Push a chunk into a body writer handle.
 *
 * Large chunks are automatically split to stay within backpressure limits.
 */
export declare function jsSendChunk(endpointHandle: number, handle: bigint, chunk: Uint8Array): Promise<void>

/** Server-side configuration passed at `serve()` time. */
export interface JsServeOptions {
  /** Maximum simultaneous in-flight requests.  Default: 1024. */
  maxConcurrency?: number
  /** Maximum connections from a single peer.  Default: 8. */
  maxConnectionsPerPeer?: number
  /** Per-request timeout in milliseconds.  Default: 60 000.  0 = disabled. */
  requestTimeout?: number
  /**
   * Reject request bodies larger than this many wire (compressed) bytes.
   * Default: 16 MiB when not set.
   */
  maxRequestBodyWireBytes?: number
  /**
   * Reject request bodies larger than this many decoded bytes (after
   * decompression). This is the compression-bomb guard.
   * Default: 16 MiB when not set.
   */
  maxRequestBodyDecodedBytes?: number
  /** Maximum total QUIC connections the server will accept.  Default: unlimited. */
  maxTotalConnections?: number
  /** Drain timeout in milliseconds after shutdown signal.  Default: 30000. */
  drainTimeout?: number
  /** Enable load-shedding (reject with 503 when at capacity). */
  loadShed?: boolean
  /**
   * When `true` (the default), automatically decompress compressed request
   * bodies.  Set to `false` to receive raw wire bytes (proxy use-cases).
   */
  decompress?: boolean
}

/** A service to advertise via generic DNS-SD (no iroh endpoint involved). */
export interface JsServiceConfig {
  /** Bare service name, e.g. `"my-app"` → `_my-app._udp.local.`. */
  serviceName: string
  /** DNS-SD instance label. */
  instanceName: string
  /** SRV port peers connect to. */
  port: number
  /** Extra IP addresses to advertise (local interface addrs added auto). */
  addrs: Array<string>
  /** TXT key/value properties. */
  txt: Record<string, string>
  /** `"udp"` (default) or `"tcp"`. */
  protocol?: string
}

/** A fully-resolved DNS-SD service record returned by `browseNext`. */
export interface JsServiceRecord {
  /** `true` = appeared/updated; `false` = expired. */
  isActive: boolean
  /** Service type and domain, e.g. `_my-app._udp.local.`. */
  serviceType: string
  /** Service instance label. */
  instanceName: string
  /** Host name (absent on expiry). */
  host?: string
  /** SRV port (`0` on expiry). */
  port: number
  /** Resolved socket addresses (empty on expiry). */
  addrs: Array<string>
  /** All TXT key/value properties (empty on expiry). */
  txt: Record<string, string>
}

/**
 * Accept an incoming session (QUIC connection) from a remote peer.
 *
 * Blocks until a peer connects or the endpoint shuts down.  Returns
 * `{ sessionHandle, nodeId }` on success, or `null` when the endpoint is closed.
 */
export interface JsSessionAccepted {
  sessionHandle: bigint
  nodeId: string
}

/** Open a new bidirectional stream on an existing session. */
export interface JsSessionBidiStream {
  readHandle: bigint
  writeHandle: bigint
}

/**
 * Non-blocking body read fast path.
 *
 * Returns:
 * - `Ok(Some(chunk))` — data was available synchronously.
 * - `Ok(None)` — EOF, handle cleaned up.
 * - `Err(_)` — channel empty or lock contended, caller should fall back to async `nextChunk`.
 */
export declare function jsTryNextChunk(endpointHandle: number, handle: bigint): Buffer | null

/**
 * Subscribe to path changes for a specific peer.
 * Returns the next path change as a JSON string, or null when done.
 * Call repeatedly to receive successive changes; the endpoint de-duplicates
 * watcher tasks so concurrent calls for the same peer share one Rust task.
 */
export declare function nextPathChange(endpointHandle: number, nodeId: string): Promise<string | null>

/** Full node address: node ID + relay URL(s) + direct socket addresses. */
export declare function nodeAddr(endpointHandle: number): JsNodeAddrInfo

/**
 * Generate a ticket string for the given endpoint.
 *
 * The ticket encodes the node ID and all known addresses (relay URLs + direct IPs).
 * Share with peers so they can connect directly.
 */
export declare function nodeTicket(endpointHandle: number): string

/** Known addresses for a remote peer, or null if unknown. */
export declare function peerInfo(endpointHandle: number, nodeId: string): Promise<JsNodeAddrInfo | null>

/** Per-peer connection statistics with path information. */
export declare function peerStats(endpointHandle: number, nodeId: string): Promise<JsPeerStats | null>

/**
 * Verify a 64-byte Ed25519 signature against a 32-byte public key.
 * Returns `true` on success, `false` on failure — does not throw.
 */
export declare function publicKeyVerify(publicKey: Uint8Array, data: Uint8Array, signature: Uint8Array): boolean

/**
 * Send an HTTP request to a remote Iroh peer.
 *
 * Low-level function — the shared TS layer wraps this in `makeFetch`.
 */
export declare function rawFetch(endpointHandle: number, nodeId: string, url: string, method: string, headers: Array<Array<string>>, reqBodyHandle: bigint | undefined | null, fetchToken: bigint, directAddrs?: Array<string> | undefined | null, timeoutMs?: number | undefined | null, decompress?: boolean | undefined | null, maxResponseBodyBytes?: number | undefined | null): Promise<JsFfiResponse>

/**
 * Call once per request from the JS handler to send the response head.
 *
 * This is the Node.js equivalent of Tauri's `respond_to_request` command.
 * The handler callback in `rawServe` is fire-and-forget (napi-rs does not
 * support awaiting Promise return values from ThreadsafeFunction callbacks),
 * so JS must call `rawRespond` explicitly after computing the response head.
 */
export declare function rawRespond(endpointHandle: number, reqHandle: bigint, status: number, headers: Array<Array<string>>): void

export declare function rawServe(endpointHandle: number, serveOptions: JsServeOptions | undefined | null, handler: ((arg: JsCallArgs) => void), onConnectionEvent?: (((arg: JsConnectionEvent) => void)) | undefined | null): Promise<void>

/**
 * Sign arbitrary bytes with a 32-byte Ed25519 secret key.
 * Returns a 64-byte signature as a `Buffer`.
 */
export declare function secretKeySign(secretKey: Uint8Array, data: Uint8Array): Buffer

export declare function sessionAccept(endpointHandle: number): Promise<JsSessionAccepted | null>

export declare function sessionClosed(endpointHandle: number, sessionHandle: bigint): Promise<JsCloseInfo>

/** Close a session. */
export declare function sessionCloseHandle(endpointHandle: number, sessionHandle: bigint, closeCode?: bigint | undefined | null, reason?: string | undefined | null): Promise<void>

/**
 * Establish a session (QUIC connection) to a remote peer.
 * Returns an opaque session handle.
 */
export declare function sessionConnect(endpointHandle: number, nodeId: string, directAddrs?: Array<string> | undefined | null): Promise<bigint>

export declare function sessionCreateBidiStream(endpointHandle: number, sessionHandle: bigint): Promise<JsSessionBidiStream>

/**
 * Open a new unidirectional (send-only) stream on a session.
 * Returns a write handle.
 */
export declare function sessionCreateUniStream(endpointHandle: number, sessionHandle: bigint): Promise<bigint>

/**
 * Get the maximum datagram payload size for a session.
 * Returns null if datagrams are not supported.
 */
export declare function sessionMaxDatagramSize(endpointHandle: number, sessionHandle: bigint): number | null

/**
 * Accept the next incoming bidirectional stream on a session.
 * Returns null when the session is closed.
 */
export declare function sessionNextBidiStream(endpointHandle: number, sessionHandle: bigint): Promise<JsSessionBidiStream | null>

/**
 * Accept the next incoming unidirectional stream on a session.
 * Returns a read handle, or null when the session is closed.
 */
export declare function sessionNextUniStream(endpointHandle: number, sessionHandle: bigint): Promise<bigint | null>

/** Receive the next datagram on a session. Returns null when the session closes. */
export declare function sessionRecvDatagram(endpointHandle: number, sessionHandle: bigint): Promise<Buffer | null>

/** Send a datagram on a session. */
export declare function sessionSendDatagram(endpointHandle: number, sessionHandle: bigint, data: Uint8Array): Promise<void>

/**
 * Register a push callback for transport-level events.
 *
 * Spawns a Tokio task that drains the endpoint's event channel and calls
 * `handler` on the Node.js thread for each event (JSON-serialised string).
 * The task exits automatically when the endpoint closes (all senders drop).
 * Call at most once per endpoint; subsequent calls return an error.
 */
export declare function startTransportEvents(endpointHandle: number, handler: ((arg: string) => void)): Promise<void>

/**
 * Stop the serve loop for the given endpoint (graceful shutdown).
 *
 * This signals the accept loop to stop but does NOT close the endpoint or
 * drain in-flight requests.  Call `closeEndpoint` afterwards if you want
 * a full teardown.
 *
 * If the endpoint handle is already gone (e.g. the node was closed), this
 * is a no-op — the serve loop is already stopped.
 */
export declare function stopServe(endpointHandle: number): void

/** Unsubscribe from path changes for a specific peer. */
export declare function unsubscribePathChanges(endpointHandle: number, nodeId: string): void

/**
 * Wait until this endpoint has been fully closed — either because `closeEndpoint()`
 * was called or because the QUIC stack shut down natively.
 *
 * This is used to surface `node.closed` reliably even without an explicit `close()`.
 */
export declare function waitEndpointClosed(endpointHandle: number): Promise<void>

/**
 * Wait until the serve loop has fully exited (all in-flight requests drained).
 *
 * Resolves immediately if `rawServe` was never called on this endpoint.
 * Call this after `stopServe` to confirm the loop has actually terminated.
 *
 * If the endpoint handle is already gone (e.g. the node was closed), this
 * resolves immediately — the serve loop is already stopped.
 */
export declare function waitServeStop(endpointHandle: number): Promise<void>
