/**
 * iroh-http-node — Node.js entry point.
 *
 * Wires the napi-rs native addon to iroh-http-shared and exports `createNode`.
 *
 * ```ts
 * import { createNode } from 'iroh-http-node';
 *
 * const node = await createNode({ key: savedKey });
 * node.serve({}, req => new Response('hello'));
 * const res = await node.fetch(peerId, '/api');
 * ```
 */

// The napi-rs build tool generates this file at build time.
// It loads the correct platform-specific .node binary.
import {
  createEndpoint,
  closeEndpoint,
  jsNextChunk,
  jsSendChunk,
  jsFinishBody,
  jsAllocBodyWriter,
  jsCancelRequest,
  jsNextTrailer,
  jsSendTrailers,
  jsAllocFetchToken,
  jsCancelInFlight,
  rawFetch as napiRawFetch,
  rawServe as napiRawServe,
  rawRespond as napiRawRespond,
  rawConnect as napiRawConnect,
  stopServe as napiStopServe,
  nodeAddr as napiNodeAddr,
  nodeTicket as napiNodeTicket,
  homeRelay as napiHomeRelay,
  peerInfo as napiPeerInfo,
  peerStats as napiPeerStats,
  mdnsBrowse as napiMdnsBrowse,
  mdnsNextEvent as napiMdnsNextEvent,
  mdnsBrowseClose as napiMdnsBrowseClose,
  mdnsAdvertise as napiMdnsAdvertise,
  mdnsAdvertiseClose as napiMdnsAdvertiseClose,
  sessionConnect as napiSessionConnect,
  sessionCreateBidiStream as napiSessionCreateBidiStream,
  sessionNextBidiStream as napiSessionNextBidiStream,
  sessionCloseHandle as napiSessionClose,
  sessionClosed as napiSessionClosed,
  sessionCreateUniStream as napiSessionCreateUniStream,
  sessionNextUniStream as napiSessionNextUniStream,
  sessionSendDatagram as napiSessionSendDatagram,
  sessionRecvDatagram as napiSessionRecvDatagram,
  sessionMaxDatagramSize as napiSessionMaxDatagramSize,
} from "./index.js";  // generated by napi build

import {
  buildNode,
  type AddrFunctions,
  type DiscoveryFunctions,
  type Bridge,
  type RawFetchFn,
  type RawServeFn,
  type RawConnectFn,
  type RawSessionFns,
  type AllocBodyWriterFn,
  type NodeOptions,
  type IrohNode,
  type NodeAddrInfo,
  type FfiResponse,
  type FfiDuplexStream,
  type RequestPayload,
  type FfiResponseHead,
  classifyBindError,
  type SecretKey,
} from "@momics/iroh-http-shared";

// ── Bridge implementation ─────────────────────────────────────────────────────

const bridge: Bridge = {
  nextChunk: (handle: number) => jsNextChunk(handle),
  sendChunk: (handle: number, chunk: Uint8Array) => jsSendChunk(handle, chunk),
  finishBody: (handle: number) => {
    jsFinishBody(handle);
    return Promise.resolve();
  },
  cancelRequest: (handle: number) => {
    jsCancelRequest(handle);
    return Promise.resolve();
  },
  allocFetchToken: () => Promise.resolve(jsAllocFetchToken()),
  cancelFetch: (token: number) => { jsCancelInFlight(token); },
  nextTrailer: async (handle: number) => {
    const rows = await jsNextTrailer(handle);
    return rows ? (rows as string[][]).map((p) => [p[0], p[1]] as [string, string]) : null;
  },
  sendTrailers: (handle: number, trailers: [string, string][]) => {
    jsSendTrailers(handle, trailers as string[][]);
    return Promise.resolve();
  },
};

// ── Platform function adapters ────────────────────────────────────────────────

const rawFetch: RawFetchFn = async (
  endpointHandle,
  nodeId,
  url,
  method,
  headers,
  reqBodyHandle,
  fetchToken,
  directAddrs
) => {
  const res = await napiRawFetch(
    endpointHandle,
    nodeId,
    url,
    method,
    headers as string[][],
    reqBodyHandle ?? null,
    fetchToken,
    directAddrs ?? null
  );
  return {
    status: res.status,
    headers: res.headers as [string, string][],
    bodyHandle: res.bodyHandle,
    url: res.url,
    trailersHandle: res.trailersHandle,
  } satisfies FfiResponse;
};

const rawServe: RawServeFn = (
  endpointHandle,
  _options,
  callback: (payload: RequestPayload) => Promise<FfiResponseHead>
) => {
  napiRawServe(
    endpointHandle,
    (payload: Record<string, unknown>) => {
      const typed = payload as unknown as RequestPayload;
      // napi-rs's ThreadsafeFunction does not await Promise return values,
      // so we handle the async work here and call rawRespond explicitly.
      callback(typed)
        .then((head) => {
          napiRawRespond(typed.reqHandle, head.status, head.headers as string[][]);
        })
        .catch((err: unknown) => {
          console.error("[iroh-http-node] serve handler error:", err);
          napiRawRespond(typed.reqHandle, 500, []);
        });
    }
  );
};

const allocBodyWriter: AllocBodyWriterFn = () => jsAllocBodyWriter();

const rawConnect: RawConnectFn = async (
  endpointHandle,
  nodeId,
  path,
  headers
) => {
  const ffi = await napiRawConnect(
    endpointHandle,
    nodeId,
    path,
    headers as string[][]
  );
  return {
    readHandle: ffi.readHandle,
    writeHandle: ffi.writeHandle,
  } satisfies FfiDuplexStream;
};

// ── Public API ────────────────────────────────────────────────────────────────

/** Normalise `relayMode` into flat fields for the Rust adapter. */
function normaliseRelayMode(mode?: import("@momics/iroh-http-shared").RelayMode): {
  relayMode: string | undefined;
  relays: string[] | undefined;
  disableNetworking: boolean;
} {
  if (mode === "disabled") return { relayMode: "disabled", relays: [], disableNetworking: true };
  if (mode === "default" || mode === undefined) return { relayMode: undefined, relays: undefined, disableNetworking: false };
  if (mode === "staging") return { relayMode: "staging", relays: undefined, disableNetworking: false };
  if (Array.isArray(mode)) return { relayMode: "custom", relays: mode, disableNetworking: false };
  return { relayMode: "custom", relays: [mode], disableNetworking: false };
}

/** Normalise DiscoveryOptions into flat fields for the Rust adapter. */
function normaliseDiscovery(disc?: import("@momics/iroh-http-shared").DiscoveryOptions): {
  dnsEnabled: boolean;
} {
  if (!disc) return { dnsEnabled: true };
  const dnsEnabled = disc.dns !== false;
  return { dnsEnabled };
}

/** Address introspection functions backed by napi bindings. */
const addrFns: AddrFunctions = {
  nodeAddr: async (handle) => {
    const info = napiNodeAddr(handle);
    return { id: info.id, addrs: info.addrs } satisfies NodeAddrInfo;
  },
  nodeTicket: async (handle) => napiNodeTicket(handle),
  homeRelay: async (handle) => napiHomeRelay(handle) ?? null,
  peerInfo: async (handle, nodeId) => {
    const info = await napiPeerInfo(handle, nodeId);
    return info ? { id: info.id, addrs: info.addrs } satisfies NodeAddrInfo : null;
  },
  peerStats: async (handle, nodeId) => {
    const stats = await napiPeerStats(handle, nodeId);
    return stats ?? null;
  },
};

/** Discovery functions backed by napi bindings. */
const discoveryFns: DiscoveryFunctions = {
  mdnsBrowse: async (handle, serviceName) => napiMdnsBrowse(handle, serviceName),
  mdnsNextEvent: async (browseHandle) => {
    const ev = await napiMdnsNextEvent(browseHandle);
    return ev ?? null;
  },
  mdnsBrowseClose: (browseHandle) => napiMdnsBrowseClose(browseHandle),
  mdnsAdvertise: async (handle, serviceName) => napiMdnsAdvertise(handle, serviceName),
  mdnsAdvertiseClose: (advertiseHandle) => napiMdnsAdvertiseClose(advertiseHandle),
};

/** Session functions backed by napi bindings. */
const nodeSessionFns: RawSessionFns = {
  connect: async (endpointHandle, nodeId, directAddrs) =>
    napiSessionConnect(endpointHandle, nodeId, directAddrs ?? undefined),
  createBidiStream: async (sessionHandle) => {
    const ffi = await napiSessionCreateBidiStream(sessionHandle);
    return { readHandle: ffi.readHandle, writeHandle: ffi.writeHandle } satisfies FfiDuplexStream;
  },
  nextBidiStream: async (sessionHandle) => {
    const ffi = await napiSessionNextBidiStream(sessionHandle);
    return ffi ? { readHandle: ffi.readHandle, writeHandle: ffi.writeHandle } satisfies FfiDuplexStream : null;
  },
  createUniStream: async (sessionHandle) => napiSessionCreateUniStream(sessionHandle),
  nextUniStream: async (sessionHandle) => napiSessionNextUniStream(sessionHandle) ?? null,
  sendDatagram: async (sessionHandle, data) => napiSessionSendDatagram(sessionHandle, data),
  recvDatagram: async (sessionHandle) => {
    const buf = await napiSessionRecvDatagram(sessionHandle);
    return buf ? new Uint8Array(buf) : null;
  },
  maxDatagramSize: async (sessionHandle) => napiSessionMaxDatagramSize(sessionHandle) ?? null,
  closed: async (sessionHandle) => {
    const info = await napiSessionClosed(sessionHandle);
    return { closeCode: info.closeCode, reason: info.reason };
  },
  close: async (sessionHandle, closeCode?, reason?) => napiSessionClose(sessionHandle, closeCode, reason),
};

/**
 * Create an Iroh node for peer-to-peer HTTP.
 *
 * @param options Optional configuration.  Omit `key` to generate a fresh identity.
 */
export async function createNode(options?: NodeOptions): Promise<IrohNode> {
  const keyBytes = options?.key
    ? (options.key instanceof Uint8Array ? options.key : (options.key as SecretKey).toBytes())
    : undefined;

  const { relayMode, relays, disableNetworking } = normaliseRelayMode(options?.relayMode);
  const discovery = normaliseDiscovery(options?.discovery);
  const bindAddrs = options?.bindAddr
    ? (Array.isArray(options.bindAddr) ? options.bindAddr : [options.bindAddr])
    : undefined;

  const info = await createEndpoint(
    options
      ? {
          key: keyBytes,
          idleTimeout: options.idleTimeout,
          relayMode,
          relays,
          bindAddrs,
          dnsDiscovery: options.dnsDiscovery,
          dnsDiscoveryEnabled: discovery.dnsEnabled,
          channelCapacity: options.channelCapacity,
          maxChunkSizeBytes: options.maxChunkSizeBytes,
          maxConsecutiveErrors: options.maxConsecutiveErrors,
          drainTimeout: options.drainTimeout,
          handleTtl: options.handleTtl,
          disableNetworking,
          proxyUrl: options.proxyUrl,
          proxyFromEnv: options.proxyFromEnv,
          keylog: options.keylog,
          compressionLevel: typeof options.compression === "object"
            ? options.compression.level
            : options.compression ? 3 : undefined,
          compressionMinBodyBytes: typeof options.compression === "object"
            ? options.compression.minBodyBytes
            : undefined,
          maxConcurrency: options.maxConcurrency,
          maxConnectionsPerPeer: options.maxConnectionsPerPeer,
          requestTimeout: options.requestTimeout,
          maxRequestBodyBytes: options.maxRequestBodyBytes,
          maxHeaderBytes: options.maxHeaderBytes,
        }
      : undefined
  ).catch((e: unknown) => { throw classifyBindError(e); });

  return buildNode(
    bridge,
    {
      endpointHandle: info.endpointHandle,
      nodeId: info.nodeId,
      keypair: info.keypair as Uint8Array,
    },
    rawFetch,
    rawServe,
    rawConnect,
    allocBodyWriter,
    (handle, force?) => closeEndpoint(handle, force ?? null),
    (handle) => napiStopServe(handle),
    addrFns,
    discoveryFns,
    nodeSessionFns,
  );
}
