/**
 * iroh-http-node — Node.js entry point.
 *
 * Wires the napi-rs native addon to iroh-http-shared and exports `createNode`.
 *
 * ```ts
 * import { createNode } from 'iroh-http-node';
 *
 * const node = await createNode({ key: savedKey });
 * node.serve({}, req => new Response('hello'));
 * const res = await node.fetch(peerId, '/api');
 * ```
 */

// The napi-rs build tool generates this file at build time.
// It loads the correct platform-specific .node binary.
import {
  closeEndpoint,
  createEndpoint,
  homeRelay as napiHomeRelay,
  jsAllocBodyWriter,
  jsAllocFetchToken,
  jsCancelInFlight,
  jsCancelRequest,
  jsFinishBody,
  jsNextChunk,
  jsSendChunk,
  mdnsAdvertise as napiMdnsAdvertise,
  mdnsAdvertiseClose as napiMdnsAdvertiseClose,
  mdnsBrowse as napiMdnsBrowse,
  mdnsBrowseClose as napiMdnsBrowseClose,
  mdnsNextEvent as napiMdnsNextEvent,
  nodeAddr as napiNodeAddr,
  nodeTicket as napiNodeTicket,
  peerInfo as napiPeerInfo,
  peerStats as napiPeerStats,
  endpointStats as napiEndpointStats,
  rawConnect as napiRawConnect,
  rawFetch as napiRawFetch,
  rawRespond as napiRawRespond,
  rawServe as napiRawServe,
  sessionClosed as napiSessionClosed,
  sessionCloseHandle as napiSessionClose,
  sessionConnect as napiSessionConnect,
  sessionCreateBidiStream as napiSessionCreateBidiStream,
  sessionCreateUniStream as napiSessionCreateUniStream,
  sessionMaxDatagramSize as napiSessionMaxDatagramSize,
  sessionNextBidiStream as napiSessionNextBidiStream,
  sessionNextUniStream as napiSessionNextUniStream,
  sessionRecvDatagram as napiSessionRecvDatagram,
  sessionSendDatagram as napiSessionSendDatagram,
  stopServe as napiStopServe,
  waitServeStop as napiWaitServeStop,
  waitEndpointClosed as napiWaitEndpointClosed,
} from "./index.js"; // generated by napi build

import {
  type AddrFunctions,
  buildNode,
  classifyBindError,
  type DiscoveryFunctions,
  type IrohNode,
  type NodeAddrInfo,
  type NodeOptions,
  normaliseRelayMode,
  type SecretKey,
} from "@momics/iroh-http-shared";
import type {
  AllocBodyWriterFn,
  Bridge,
  FfiDuplexStream,
  FfiResponse,
  FfiResponseHead,
  RawConnectFn,
  RawFetchFn,
  RawServeFn,
  RawSessionFns,
  RequestPayload,
} from "@momics/iroh-http-shared/adapter";

// ── Graceful shutdown tracking ─────────────────────────────────────────────────
// Track all live endpoint handles so SIGTERM/SIGINT handlers can close them.
// This sends QUIC CONNECTION_CLOSE frames so peers observe a clean disconnect.
const _liveEndpoints = new Set<number>();

function _closeAllEndpoints(signal: string): void {
  const handles = [..._liveEndpoints];
  _liveEndpoints.clear();
  if (handles.length === 0) return;
  // Force-close all handles and exit after they drain (or after 2 s).
  const deadline = setTimeout(() => process.exit(128 + (signal === "SIGTERM" ? 15 : 2)), 2000);
  if (deadline.unref) deadline.unref();
  Promise.all(handles.map((h) => closeEndpoint(h, true).catch(() => {}))).then(() => {
    process.exit(0);
  });
}

process.once("SIGTERM", () => _closeAllEndpoints("SIGTERM"));
process.once("SIGINT", () => _closeAllEndpoints("SIGINT"));

// ── Bridge implementation ─────────────────────────────────────────────────────
// Constructed per-node inside createNode() to close over endpointHandle.

// ── Platform function adapters ────────────────────────────────────────────────

const rawFetch: RawFetchFn = async (
  endpointHandle,
  nodeId,
  url,
  method,
  headers,
  reqBodyHandle,
  fetchToken,
  directAddrs,
) => {
  const res = await (napiRawFetch as (
    endpointHandle: number,
    nodeId: string,
    url: string,
    method: string,
    headers: string[][],
    reqBodyHandle: bigint | null,
    fetchToken: bigint,
    directAddrs: string[] | null,
  ) => Promise<{
    status: number;
    headers: string[][];
    bodyHandle: bigint;
    url: string;
  }>)(
    endpointHandle,
    nodeId,
    url,
    method,
    headers as string[][],
    reqBodyHandle ?? null,
    fetchToken,
    directAddrs ?? null,
  );
  return {
    status: res.status,
    headers: res.headers as [string, string][],
    bodyHandle: res.bodyHandle,
    url: res.url,
  } satisfies FfiResponse;
};

const rawServe: RawServeFn = (
  endpointHandle,
  options,
  callback: (payload: RequestPayload) => Promise<FfiResponseHead>,
): Promise<void> => {
  // Cast napiRawServe to include the optional third argument that will exist
  // in the napi-generated types after the next build.
  (napiRawServe as (
    handle: number,
    cb: ((payload: Record<string, unknown>) => void),
    onConnEv: ((ev: { peerId: string; connected: boolean }) => void) | null,
  ) => void)(
    endpointHandle,
    (payload: Record<string, unknown>) => {
      const typed = payload as unknown as RequestPayload;
      // napi-rs's ThreadsafeFunction does not await Promise return values,
      // so we handle the async work here and call rawRespond explicitly.
      callback(typed)
        .then((head) => {
          try {
            napiRawRespond(
              endpointHandle,
              typed.reqHandle,
              head.status,
              head.headers as string[][],
            );
          } catch (respondErr) {
            console.error("[iroh-http-node] rawRespond failed:", respondErr);
          }
        })
        .catch((err: unknown) => {
          console.error("[iroh-http-node] serve handler error:", err);
          try {
            napiRawRespond(endpointHandle, typed.reqHandle, 500, []);
          } catch (respondErr) {
            console.error("[iroh-http-node] rawRespond (fallback 500) failed:", respondErr);
          }
        });
    },
    options.onConnectionEvent ?? null,
  );
  // Return a promise that resolves when the native serve loop has fully
  // exited (stopServe() was called and all in-flight requests drained).
  return napiWaitServeStop(endpointHandle);
};

// allocBodyWriter constructed per-node inside createNode() to close over endpointHandle.

const rawConnect: RawConnectFn = async (
  endpointHandle,
  nodeId,
  path,
  headers,
) => {
  const ffi = await napiRawConnect(
    endpointHandle,
    nodeId,
    path,
    headers as string[][],
  );
  return {
    readHandle: ffi.readHandle,
    writeHandle: ffi.writeHandle,
  } satisfies FfiDuplexStream;
};

// ── Public API ────────────────────────────────────────────────────────────────

/** Normalise the `discovery` option into flat fields for the Rust adapter. */
function normaliseDiscovery(disc?: NodeOptions["discovery"]): {
  dnsEnabled: boolean;
  dnsServerUrl?: string;
} {
  if (!disc) return { dnsEnabled: true };
  if (disc.dns === false) return { dnsEnabled: false };
  if (typeof disc.dns === "object" && disc.dns !== null) {
    return { dnsEnabled: true, dnsServerUrl: disc.dns.serverUrl };
  }
  return { dnsEnabled: true };
}

/** Address introspection functions backed by napi bindings. */
const addrFns: AddrFunctions = {
  nodeAddr: async (handle) => {
    const info = napiNodeAddr(handle);
    return { id: info.id, addrs: info.addrs } satisfies NodeAddrInfo;
  },
  nodeTicket: async (handle) => napiNodeTicket(handle),
  homeRelay: async (handle) => napiHomeRelay(handle) ?? null,
  peerInfo: async (handle, nodeId) => {
    const info = await napiPeerInfo(handle, nodeId);
    return info
      ? ({ id: info.id, addrs: info.addrs } satisfies NodeAddrInfo)
      : null;
  },
  peerStats: async (handle, nodeId) => {
    const stats = await napiPeerStats(handle, nodeId);
    if (!stats) return null;
    return {
      relay: stats.relay,
      relayUrl: stats.relayUrl ?? null,
      paths: stats.paths,
      rttMs: stats.rttMs ?? null,
      bytesSent: stats.bytesSent ?? null,
      bytesReceived: stats.bytesReceived ?? null,
      lostPackets: stats.lostPackets ?? null,
      sentPackets: stats.sentPackets ?? null,
      congestionWindow: stats.congestionWindow ?? null,
    };
  },
  stats: async (handle) => {
    const s = napiEndpointStats(handle);
    return {
      activeReaders: Number(s.activeReaders),
      activeWriters: Number(s.activeWriters),
      activeSessions: Number(s.activeSessions),
      totalHandles: Number(s.totalHandles),
      poolSize: Number(s.poolSize),
      activeConnections: Number(s.activeConnections),
      activeRequests: Number(s.activeRequests),
    };
  },
};

/** Discovery functions backed by napi bindings. */
const discoveryFns: DiscoveryFunctions = {
  mdnsBrowse: async (handle, serviceName) =>
    napiMdnsBrowse(handle, serviceName),
  mdnsNextEvent: async (browseHandle) => {
    const ev = await napiMdnsNextEvent(browseHandle);
    if (!ev) return null;
    return {
      type: ev.isActive ? "discovered" : "expired",
      nodeId: ev.nodeId,
      addrs: ev.addrs,
    };
  },
  mdnsBrowseClose: (browseHandle) => napiMdnsBrowseClose(browseHandle),
  mdnsAdvertise: async (handle, serviceName) =>
    napiMdnsAdvertise(handle, serviceName),
  mdnsAdvertiseClose: (advertiseHandle) =>
    napiMdnsAdvertiseClose(advertiseHandle),
};

// Session functions constructed per-node inside createNode() to close over endpointHandle.

/**
 * Create an Iroh node for peer-to-peer HTTP.
 *
 * @param options Optional configuration.  Omit `key` to generate a fresh identity.
 */
export { PublicKey, SecretKey } from "@momics/iroh-http-shared";
export type { IrohNode, NodeOptions };

export async function createNode(options?: NodeOptions): Promise<IrohNode> {
  const keyBytes = options?.key
    ? options.key instanceof Uint8Array
      ? options.key
      : (options.key as SecretKey).toBytes()
    : undefined;

  // NODE-001: merge the relay-mode-derived value with the explicit option so
  // that createNode({ disableNetworking: true }) is respected regardless of relayMode.
  const { relayMode, relays, disableNetworking } = normaliseRelayMode(
    options?.relayMode,
  );
  const discovery = normaliseDiscovery(options?.discovery);
  const disableNetworkingFinal =
    disableNetworking || (options?.disableNetworking ?? false);
  const bindAddrs = options?.bindAddr
    ? Array.isArray(options.bindAddr) ? options.bindAddr : [options.bindAddr]
    : undefined;

  const info = await createEndpoint(
    options
      ? {
        key: keyBytes,
        idleTimeout: options.idleTimeout,
        relayMode,
        relays: relays ?? undefined,
        bindAddrs,
        dnsDiscovery: discovery.dnsServerUrl ?? undefined,
        dnsDiscoveryEnabled: discovery.dnsEnabled,
        channelCapacity: options.advanced?.channelCapacity,
        maxChunkSizeBytes: options.advanced?.maxChunkSizeBytes,
        maxConsecutiveErrors: options.advanced?.maxConsecutiveErrors,
        drainTimeout: options.advanced?.drainTimeout,
        handleTtl: options.advanced?.handleTtl,
        maxPooledConnections: options.maxPooledConnections,
        poolIdleTimeoutMs: options.poolIdleTimeoutMs,
        disableNetworking: disableNetworkingFinal,
        proxyUrl: options.proxyUrl,
        proxyFromEnv: options.proxyFromEnv,
        keylog: options.keylog,
        compressionLevel: typeof options.compression === "object"
          ? options.compression.level
          : options.compression
          ? 3
          : undefined,
        compressionMinBodyBytes: typeof options.compression === "object"
          ? options.compression.minBodyBytes
          : undefined,
        maxConcurrency: options.maxConcurrency,
        maxConnectionsPerPeer: options.maxConnectionsPerPeer,
        requestTimeout: options.requestTimeout,
        maxRequestBodyBytes: options.maxRequestBodyBytes,
        maxHeaderBytes: options.maxHeaderBytes,
        maxTotalConnections: options.maxTotalConnections,
      }
      : undefined,
  ).catch((e: unknown) => {
    throw classifyBindError(e);
  });

  const eh = info.endpointHandle;
  _liveEndpoints.add(eh);

  // Bridge: close over endpointHandle so body-handle napi calls get it.
  const nodeBridge: Bridge = {
    nextChunk: (handle: bigint) => jsNextChunk(eh, handle),
    sendChunk: (handle: bigint, chunk: Uint8Array) => jsSendChunk(eh, handle, chunk),
    finishBody: (handle: bigint) => {
      jsFinishBody(eh, handle);
      return Promise.resolve();
    },
    cancelRequest: (handle: bigint) => {
      jsCancelRequest(eh, handle);
      return Promise.resolve();
    },
    allocFetchToken: (_endpointHandle: number) => Promise.resolve(jsAllocFetchToken(eh)),
    cancelFetch: (token: bigint) => {
      jsCancelInFlight(eh, token);
    },
  };

  const nodeAllocBodyWriter: AllocBodyWriterFn = () => jsAllocBodyWriter(eh);

  const nodeSessionFns: RawSessionFns = {
    connect: async (endpointHandle, nodeId, directAddrs) =>
      napiSessionConnect(endpointHandle, nodeId, directAddrs ?? undefined),
    createBidiStream: async (sessionHandle) => {
      const ffi = await napiSessionCreateBidiStream(eh, sessionHandle);
      return {
        readHandle: ffi.readHandle,
        writeHandle: ffi.writeHandle,
      } satisfies FfiDuplexStream;
    },
    nextBidiStream: async (sessionHandle) => {
      const ffi = await napiSessionNextBidiStream(eh, sessionHandle);
      return ffi
        ? ({ readHandle: ffi.readHandle, writeHandle: ffi.writeHandle } satisfies FfiDuplexStream)
        : null;
    },
    createUniStream: async (sessionHandle: bigint) =>
      napiSessionCreateUniStream(eh, sessionHandle),
    nextUniStream: async (sessionHandle: bigint) => {
      const h = await napiSessionNextUniStream(eh, sessionHandle);
      return h ?? null;
    },
    sendDatagram: async (sessionHandle: bigint, data: Uint8Array) =>
      napiSessionSendDatagram(eh, sessionHandle, data),
    recvDatagram: async (sessionHandle: bigint) => {
      const buf = await napiSessionRecvDatagram(eh, sessionHandle);
      return buf ? new Uint8Array(buf) : null;
    },
    maxDatagramSize: async (sessionHandle: bigint) =>
      napiSessionMaxDatagramSize(eh, sessionHandle) ?? null,
    closed: async (sessionHandle: bigint) => {
      const info = await napiSessionClosed(eh, sessionHandle);
      return { closeCode: Number(info.closeCode), reason: info.reason };
    },
    close: async (sessionHandle: bigint, closeCode?: number, reason?: string) =>
      napiSessionClose(eh, sessionHandle, closeCode !== undefined ? BigInt(closeCode) : undefined, reason),
  };

  return buildNode({
    bridge: nodeBridge,
    info: {
      endpointHandle: info.endpointHandle,
      nodeId: info.nodeId,
      keypair: info.keypair as Uint8Array,
    },
    rawFetch,
    rawServe,
    rawConnect,
    allocBodyWriter: nodeAllocBodyWriter,
    closeEndpoint: (handle: number, force?: boolean) => {
      _liveEndpoints.delete(handle);
      return closeEndpoint(handle, force ?? null);
    },
    stopServe: (handle: number) => napiStopServe(handle),
    nativeClosed: napiWaitEndpointClosed(info.endpointHandle),
    addrFns,
    discoveryFns,
    sessionFns: nodeSessionFns,
  });
}
