/**
 * Generate `src/checksums.ts` from built native libraries.
 *
 * Run at release time, after the platform `.dylib` / `.so` / `.dll` artifacts
 * have been collected into a directory (defaults to `./lib`). The emitted map
 * is what `verifyLib()` in `adapter.ts` checks downloaded binaries against, so
 * the hashes here MUST be of the exact artifacts attached to the GitHub release.
 *
 * Usage:
 *   deno run --allow-read --allow-write scripts/gen-checksums.mts [libDir] [outFile]
 */

import { resolve } from "@std/path";

const libDir = resolve(Deno.args[0] ?? "lib");

async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes as BufferSource);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

const entries: Record<string, string> = {};
for await (const entry of Deno.readDir(libDir)) {
  if (!entry.isFile) continue;
  if (!/^libiroh_http_deno\..+\.(dylib|so|dll)$/.test(entry.name)) continue;
  const bytes = await Deno.readFile(resolve(libDir, entry.name));
  entries[entry.name] = await sha256Hex(bytes);
}

const names = Object.keys(entries).sort();
if (names.length === 0) {
  console.error(`[gen-checksums] No native libraries found in ${libDir}`);
  Deno.exit(1);
}

const body = names
  .map((name) => `  ${JSON.stringify(name)}: ${JSON.stringify(entries[name])},`)
  .join("\n");

const out = `/**
 * SHA-256 integrity checksums for the prebuilt native libraries published with
 * each release. Maps the platform-specific library filename to its lowercase
 * hex SHA-256 digest.
 *
 * GENERATED by scripts/gen-checksums.mts — do not edit by hand. Native FFI code
 * runs outside Deno's permission sandbox, so verifying this digest before
 * \`Deno.dlopen()\` is what stands between a tampered binary and RCE.
 */
export const NATIVE_CHECKSUMS: Record<string, string> = {
${body}
};
`;

const dest = Deno.args[1]
  ? resolve(Deno.args[1])
  : resolve(import.meta.dirname ?? ".", "..", "src", "checksums.ts");
await Deno.writeTextFile(dest, out);
console.error(`[gen-checksums] Wrote ${names.length} checksum(s) to ${dest}`);
for (const name of names) console.error(`  ${name}  ${entries[name]}`);
