"""Type stubs for the iroh-http Python package."""

from typing import Any, Optional

def create_node(
    key: Optional[bytes] = None,
    idle_timeout: Optional[int] = None,
    relays: Optional[list[str]] = None,
    dns_discovery: Optional[str] = None,
    disable_networking: bool = False,
    relay_mode: Optional[str] = None,
    bind_addrs: Optional[list[str]] = None,
    proxy_url: Optional[str] = None,
    proxy_from_env: bool = False,
    keylog: bool = False,
    compression_level: Optional[int] = None,
    compression_min_body_bytes: Optional[int] = None,
    max_concurrency: Optional[int] = None,
    max_connections_per_peer: Optional[int] = None,
    request_timeout: Optional[int] = None,
    max_request_body_bytes: Optional[int] = None,
) -> "IrohNode": ...
"""Create and bind an Iroh peer-to-peer HTTP node."""

def secret_key_sign(secret_key: bytes, data: bytes) -> bytes: ...
"""Sign data with a 32-byte Ed25519 secret key. Returns a 64-byte signature."""

def public_key_verify(public_key: bytes, data: bytes, signature: bytes) -> bool: ...
"""Verify a 64-byte Ed25519 signature against a 32-byte public key."""

def generate_secret_key() -> bytes: ...
"""Generate a fresh Ed25519 secret key (32 bytes)."""

class HandlerResponse:
    """Structured response returned by a serve handler.

    Use instead of a plain dict for type-safe response construction::

        return HandlerResponse(status=200, headers=[("content-type", "text/plain")], body=b"ok")
    """

    def __init__(
        self,
        status: int = 200,
        headers: Optional[list[tuple[str, str]]] = None,
        body: Optional[bytes] = None,
    ) -> None: ...

    @property
    def status(self) -> int: ...
    @property
    def headers(self) -> list[tuple[str, str]]: ...
    @property
    def body(self) -> Optional[bytes]: ...

class IrohResponse:
    """Response returned by ``IrohNode.fetch``."""

    @property
    def status(self) -> int: ...
    @property
    def headers(self) -> list[tuple[str, str]]: ...
    @property
    def url(self) -> str: ...

    async def bytes(self) -> bytes: ...
    async def text(self) -> str: ...
    async def json(self) -> Any: ...

class IrohRequest:
    """Incoming request passed to the ``serve`` handler."""

    @property
    def method(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def remote_node_id(self) -> str: ...
    @property
    def headers(self) -> list[tuple[str, str]]: ...

    async def body(self) -> bytes: ...

class IrohUniStream:
    """A unidirectional (send-only) byte stream."""

    async def write(self, data: bytes) -> None: ...
    def close(self) -> None: ...

class IrohBidiStream:
    """A bidirectional byte stream."""

    async def write(self, data: bytes) -> None: ...
    async def read(self) -> Optional[bytes]: ...
    def close(self) -> None: ...

    def __aiter__(self) -> "IrohBidiStream": ...
    async def __anext__(self) -> bytes: ...

class IrohSession:
    """A session (QUIC connection) to a single remote peer."""

    async def create_bidirectional_stream(self) -> IrohBidiStream: ...
    async def create_unidirectional_stream(self) -> IrohUniStream: ...
    async def send_datagram(self, data: bytes) -> None: ...
    async def recv_datagram(self) -> Optional[bytes]: ...

    @property
    def max_datagram_size(self) -> Optional[int]: ...

    # PY-008: close() is async at runtime — mark it async here.
    async def close(self, close_code: int = 0, reason: str = "") -> None: ...
    async def ready(self) -> None: ...
    async def closed(self) -> tuple[int, str]: ...
    async def next_bidirectional_stream(self) -> Optional[IrohBidiStream]: ...
    async def next_unidirectional_stream(self) -> Optional[IrohBidiStream]: ...

    async def __aenter__(self) -> "IrohSession": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class IrohBrowseSession:
    """An active mDNS browse session. Iterate with ``async for event in session:``.

    Only available when the package is built with the ``mdns`` feature.
    """
    def __aiter__(self) -> "IrohBrowseSession": ...
    async def __anext__(self) -> dict: ...

class IrohServeHandle:
    """Handle returned by ``IrohNode.serve()``.

    Await ``handle.finished`` to wait for the serve loop to stop (PARITY-005).
    """
    @property
    async def finished(self) -> None: ...

class IrohNode:
    """An Iroh peer-to-peer HTTP node."""

    @property
    def node_id(self) -> str: ...
    @property
    def public_key(self) -> str:
        """Alias for ``node_id``; matches JS platforms (PARITY-002)."""
        ...
    @property
    def keypair(self) -> bytes: ...
    @property
    def secret_key(self) -> bytes:
        """Alias for ``keypair``; matches JS platforms (PARITY-002)."""
        ...

    async def connect(
        self,
        peer_id: str,
        direct_addrs: Optional[list[str]] = None,
    ) -> IrohSession: ...

    async def fetch(
        self,
        peer_id: str,
        url: str,
        method: str = "GET",
        headers: Optional[list[tuple[str, str]]] = None,
        body: Optional[bytes] = None,
        direct_addrs: Optional[list[str]] = None,
    ) -> IrohResponse: ...

    def serve(self, handler: Any) -> IrohServeHandle: ...
    def stop_serve(self) -> None: ...
    # PY-008: close() is async at runtime — mark it async here.
    async def close(self) -> None: ...
    @property
    async def closed(self) -> None:
        """Awaitable that resolves when the node has been closed (PARITY-004)."""
        ...

    def addr(self) -> tuple[str, list[str]]:
        """Synchronous in Python (unlike async in JS platforms — PARITY-006)."""
        ...
    def ticket(self) -> str:
        """Synchronous in Python (unlike async in JS platforms — PARITY-006)."""
        ...
    def home_relay(self) -> Optional[str]:
        """Synchronous in Python (unlike async in JS platforms — PARITY-006)."""
        ...
    async def peer_info(self, node_id: str) -> Optional[tuple[str, list[str]]]: ...
    async def peer_stats(self, node_id: str) -> Optional[tuple[bool, Optional[str], list[tuple[bool, str, bool]]]]: ...

    async def browse(self, service_name: str = "iroh-http") -> "IrohBrowseSession": ...
    def advertise(self, service_name: str = "iroh-http") -> None: ...

    def path_changes(self, node_id: str) -> "IrohPathChanges": ...

    async def __aenter__(self) -> "IrohNode": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class IrohPathChanges:
    """Async iterator yielding dicts whenever the relay/path to a peer changes.

    Usage::

        async for event in node.path_changes(peer_id):
            print(event["relay"], event["relay_url"])
    """
    def __aiter__(self) -> "IrohPathChanges": ...
    async def __anext__(self) -> dict[str, Any]: ...
