#!/usr/bin/env bash
# Fetch the Tauri Swift API needed for iOS builds.
#
# The .tauri/tauri-api directory is generated by `tauri ios init` at app-build
# time and is gitignored here. This script bootstraps it from the tauri-apps/tauri
# GitHub repository so iOS plugin builds work without a full Tauri app project.
#
# Usage:
#   bash scripts/setup-ios.sh              # uses pinned version
#   bash scripts/setup-ios.sh 2.10.3       # explicit version

set -euo pipefail

TAURI_VERSION="${1:-2.10.3}"
DEST="$(cd "$(dirname "$0")/.." && pwd)/.tauri/tauri-api"
TARBALL="https://github.com/tauri-apps/tauri/archive/refs/tags/tauri-v${TAURI_VERSION}.tar.gz"

if [[ -d "$DEST/Sources" ]]; then
  echo "  ⏭  .tauri/tauri-api already present (delete to re-fetch)"
  exit 0
fi

echo "  → Fetching Tauri Swift API v${TAURI_VERSION}…"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

curl -fsSL "$TARBALL" | tar -xz -C "$TMP" --strip-components=1 \
  "tauri-tauri-v${TAURI_VERSION}/core/tauri/mobile/ios-api"

mkdir -p "$(dirname "$DEST")"
mv "$TMP/core/tauri/mobile/ios-api" "$DEST"
echo "  ✓  .tauri/tauri-api → $DEST"
