//! ACL permission-set integrity tests.
//!
//! Regression guard: a hand-written permission **set** (a named group that
//! expands to several `allow-*` commands) must be declared with `[[set]]`.
//!
//! If it is mistakenly declared with `[[permission]]` and a `permissions`
//! array, Tauri parses it as an empty *leaf* permission, silently drops the
//! `permissions` list, and the resulting capability grants **nothing**. That
//! exact mistake shipped in 0.5.1: `iroh-http:fetch` (and `serve`, `connect`,
//! `crypto`, `mdns`) resolved to empty permissions, so `node.fetch()` failed
//! at runtime with `iroh-http.fetch not allowed` even though the capability
//! listed `iroh-http:fetch`.
//!
//! The bug was invisible to the build (Tauri ignores the unknown field) and to
//! every existing test (none exercised ACL resolution). These tests close that
//! gap by reading the source `.toml` files the way the schema defines them.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Named permission *sets* the plugin promises to expose, each paired with the
/// primary `allow-*` command callers depend on. If a set is renamed or a new
/// feature group is added, update this table.
fn expected_sets() -> BTreeMap<&'static str, &'static str> {
    BTreeMap::from([
        ("fetch", "allow-fetch"),
        ("serve", "allow-serve"),
        ("connect", "allow-session-connect"),
        ("crypto", "allow-secret-key-sign"),
        ("mdns", "allow-mdns-browse"),
    ])
}

fn permissions_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("permissions")
}

/// Top-level permission `.toml` files (excludes `autogenerated/` and `schemas/`).
fn hand_written_permission_files() -> Vec<PathBuf> {
    std::fs::read_dir(permissions_dir())
        .expect("permissions/ dir should exist")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|ext| ext == "toml"))
        .collect()
}

/// Every named set must be declared with `[[set]]` and expand to its primary
/// command. This fails on the 0.5.1 bug where the sets were `[[permission]]`.
#[test]
fn named_permission_sets_expand_to_their_commands() {
    let files = hand_written_permission_files();
    assert!(!files.is_empty(), "no hand-written permission files found");

    // Collect every `[[set]]` across all files: identifier -> permissions.
    let mut sets: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for path in &files {
        let raw = std::fs::read_to_string(path).expect("read permission file");
        let value: toml::Value = toml::from_str(&raw)
            .unwrap_or_else(|e| panic!("{} is not valid TOML: {e}", path.display()));

        if let Some(set_array) = value.get("set").and_then(toml::Value::as_array) {
            for set in set_array {
                let id = set
                    .get("identifier")
                    .and_then(toml::Value::as_str)
                    .unwrap_or_else(|| panic!("[[set]] without identifier in {}", path.display()));
                let perms = set
                    .get("permissions")
                    .and_then(toml::Value::as_array)
                    .map(|a| {
                        a.iter()
                            .filter_map(|v| v.as_str().map(str::to_owned))
                            .collect::<Vec<_>>()
                    })
                    .unwrap_or_default();
                sets.insert(id.to_owned(), perms);
            }
        }
    }

    for (set, primary_cmd) in expected_sets() {
        let perms = sets.get(set).unwrap_or_else(|| {
            panic!(
                "permission set `{set}` is not declared with [[set]] — it must \
                 be a [[set]], not a [[permission]], or its capability grants nothing"
            )
        });
        assert!(
            !perms.is_empty(),
            "permission set `{set}` expands to no permissions"
        );
        assert!(
            perms.iter().any(|p| p == primary_cmd),
            "permission set `{set}` is missing its primary command `{primary_cmd}`; got {perms:?}"
        );
    }
}

/// A `[[permission]]` block must never carry a `permissions` array. That is the
/// signature of the 0.5.1 bug: a set written as a permission. The `permissions`
/// field only exists on `[[set]]` / `[default]`, so its presence under
/// `[[permission]]` is always a silent-failure footgun.
#[test]
fn no_permission_block_carries_a_permissions_array() {
    for path in hand_written_permission_files() {
        let raw = std::fs::read_to_string(&path).expect("read permission file");
        let value: toml::Value = toml::from_str(&raw)
            .unwrap_or_else(|e| panic!("{} is not valid TOML: {e}", path.display()));

        if let Some(perm_array) = value.get("permission").and_then(toml::Value::as_array) {
            for perm in perm_array {
                let id = perm
                    .get("identifier")
                    .and_then(toml::Value::as_str)
                    .unwrap_or("<unknown>");
                assert!(
                    perm.get("permissions").is_none(),
                    "{}: [[permission]] `{id}` carries a `permissions` array — \
                     this should be a [[set]]. As a [[permission]] the list is \
                     silently dropped and the capability grants nothing.",
                    path.display()
                );
            }
        }
    }
}
